//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDC_NODROP                      106
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_RACKET                      131
#define IDB_BACKGROUND                  132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_LOADING                     156
#define IDB_GRASS                       158
#define IDB_MCD1                        159
#define IDB_MCL1                        160
#define IDB_MCR1                        161
#define IDB_MCU1                        162
#define IDB_BITMAP1                     163
#define IDB_DRY_DIRT                    163
#define IDB_BITMAP2                     164
#define IDB_WATER_CAN                   164
#define IDB_COIN                        165
#define IDB_INVENTORY                   166
#define IDB_BITMAP3                     168
#define IDB_LOAD_IVT_LINE               168
#define IDB_MAINUSE                     169
#define IDB_MAINUSE2                    170
#define IDB_BS_IDEL_1                   171
#define IDB_BS_IDEL_2                   172
#define IDB_BS_IDEL_3                   173
#define IDB_BS_IDEL_4                   174
#define IDB_BS_IDEL_5                   175
#define IDB_BS_IDEL_6                   176
#define IDB_TALK_BOX                    177
#define IDB_BITMAP4                     178
#define IDB_BACKPACK                    178
#define IDB_BITMAP5                     179
#define IDB_BAG_UI                      179
#define IDB_Cow_EAT_4                   179
#define IDB_TITLE                       180
#define IDB_BTitle                      181
#define IDB_BITMAP6                     182
#define IDB_MENUBACKGROUND              182
#define IDB_B_E                         183
#define IDB_B_E_C                       184
#define IDB_B_E_H                       185
#define IDB_B_O                         186
#define IDB_B_O_C                       187
#define IDB_B_O_H                       188
#define IDB_B_S_C                       189
#define IDB_BITMAP9                     190
#define IDB_B_S_H                       190
#define IDB_B_S                         191
#define IDB_IDB_LOADING                 198
#define IDB_BITMAP7                     198
#define IDB_CLOCKBAR                    198
#define IDB_BITMAP8                     199
#define IDB_BARLEY1                     201
#define IDB_BARLEY2                     202
#define IDB_BARLEY3                     203
#define IDB_BARLEY4                     204
#define IDB_BARLEY5                     205
#define IDB_BITMAP16                    206
#define IDB_BARLEY_ONHAND               206
#define IDB_PNG1                        207
#define IDB_BITMAP10                    208
#define IDB_BITMAP11                    209
#define IDB_BITMAP12                    210
#define IDB_BITMAP13                    211
#define IDB_BITMAP14                    212
#define IDB_BITMAP15                    213
#define IDB_BITMAP17                    214
#define IDB_CORN5                       215
#define IDB_CORN4                       216
#define IDB_CORN3                       217
#define IDB_CORN2                       218
#define IDB_CORN1                       219
#define IDB_CORN_ONHAND                 220
#define IDB_BITMAP18                    221
#define IDB_INVENTORY_SELECT            221
#define IDB_BITMAP19                    222
#define IDB_PAUSE                       222
#define IDB_BITMAP26                    229
#define IDB_BUSH2                       229
#define IDB_BITMAP20                    230
#define IDB_FENCE_LUNDER                237
#define IDB_FENCE_LUP                   238
#define IDB_FENCE_RUNDER                239
#define IDB_FENCE_RUP                   240
#define IDB_BITMAP33                    242
#define IDB_FENCE_BACK                  242
#define IDB_BITMAP22                    245
#define IDB_FENCE                       246
#define IDB_BITMAP23                    247
#define IDB_FENCE_STR                   247
#define IDB_BITMAP21                    248
#define IDB_LOADBACK                    248
#define IDB_BUSH                        249
#define IDB_BUSH1                       249
#define IDB_BITMAP24                    250
#define IDB_BITMAP25                    251
#define IDB_MONEYBAR                    251
#define IDB_BITMAP27                    253
#define IDB_MONEYICON                   253
#define IDB_BITMAP28                    255
#define IDB_STORE                       255
#define IDB_ChGnd                       256
#define IDB_ChWell                      257
#define IDB_BITMAP30                    259
#define IDB_ChHouse                     259
#define IDB_BITMAP29                    260
#define IDB_ChFeedbox1                  260
#define IDB_BITMAP31                    261
#define IDB_ChFeedbox2                  261
#define IDB_BITMAP32                    262
#define IDB_ChFeedbox3                  262
#define IDB_HmFood                      263
#define IDB_HmGnd                       264
#define IDB_HmWell                      265
#define IDB_HmWall                      265
#define IDB_HmWallBtm                   266
#define IDB_HmTV                        267
#define IDB_HmKettle                    268
#define IDB_HmNst                       269
#define IDB_ToolBox                     270
#define IDB_CHIC_IDEL_D                 271
#define IDB_CHIC_IDEL_L                 272
#define IDB_CHIC_IDEL_R                 273
#define IDB_CHIC_IDEL_U                 274
#define IDB_EGG                         275
#define IDB_BITMAP34                    276
#define IDB_BACKUI                      276
#define IDB_BITMAP35                    277
#define IDB_BITMAP36                    278
#define IDB_BITMAP37                    279
#define IDB_Cow_EAT_1                   280
#define IDB_Cow_EAT_2                   281
#define IDB_Cow_EAT_3                   282
#define IDB_Cow_IDEL_D                  284
#define IDB_Cow_IDEL_L                  285
#define IDB_Cow_IDEL_R                  286
#define IDB_Cow_IDEL_U                  287
#define IDB_Cow_Sleep_1                 288
#define IDB_Cow_Sleep_2                 289
#define IDB_Cow_WalkD_1                 290
#define IDB_Cow_WalkD_2                 291
#define IDB_Cow_WalkD_3                 292
#define IDB_Cow_WalkD_4                 293
#define IDB_Cow_WalkL_1                 294
#define IDB_Cow_WalkL_2                 295
#define IDB_Cow_WalkL_3                 296
#define IDB_Cow_WalkL_4                 297
#define IDB_Cow_WalkR_1                 298
#define IDB_Cow_WalkR_2                 299
#define IDB_Cow_WalkR_3                 300
#define IDB_Cow_WalkR_4                 301
#define IDB_Cow_WalkU_1                 302
#define IDB_Cow_WalkU_2                 303
#define IDB_Cow_WalkU_3                 304
#define IDB_BITMAP54                    305
#define IDB_Cow_WalkU_4                 305
#define IDB_BITMAP63                    330
#define IDB_Sheep_EAT_1                 358
#define IDB_Sheep_EAT_2                 359
#define IDB_Sheep_EAT_3                 360
#define IDB_Sheep_EAT_4                 361
#define IDB_Sheep_IDEL_D                362
#define IDB_Sheep_IDEL_L                363
#define IDB_Sheep_IDEL_R                364
#define IDB_Sheep_IDEL_U                365
#define IDB_Sheep_Sleep_1               366
#define IDB_Sheep_Sleep_2               367
#define IDB_Sheep_S_2                   367
#define IDB_Sheep_WalkD_1               368
#define IDB_Sheep_W_D1                  368
#define IDB_Sheep_WalkD_2               369
#define IDB_Sheep_W_D2                  369
#define IDB_Sheep_WalkD_3               370
#define IDB_Sheep_W_D3                  370
#define IDB_Sheep_WalkD_4               371
#define IDB_Sheep_W_D4                  371
#define IDB_Sheep_WalkL_1               372
#define IDB_Sheep_W_L1                  372
#define IDB_Sheep_WalkL_2               373
#define IDB_Sheep_W_L2                  373
#define IDB_Sheep_WalkL_3               374
#define IDB_Sheep_W_L3                  374
#define IDB_Sheep_WalkL_4               375
#define IDB_Sheep_W_L4                  375
#define IDB_Sheep_WalkR_1               376
#define IDB_Sheep_W_R1                  376
#define IDB_Sheep_WalkR_2               377
#define IDB_Sheep_W_R2                  377
#define IDB_Sheep_WalkR_3               378
#define IDB_Sheep_W_R3                  378
#define IDB_Sheep_WalkR_4               379
#define IDB_Sheep_W_R4                  379
#define IDB_Sheep_WalkU_1               380
#define IDB_Sheep_W_U1                  380
#define IDB_Sheep_WalkU_2               381
#define IDB_Sheep_W_U2                  381
#define IDB_Sheep_WalkU_3               382
#define IDB_Sheep_W_U3                  382
#define IDB_Sheep_WalkU_4               383
#define IDB_Sheep_W_U4                  383
#define IDB_Product_Milk                384
#define IDB_BITMAP39                    385
#define IDB_Product_Fleece              385
#define IDB_BITMAP38                    387
#define IDB_Road_CDown                  388
#define IDB_Road_Center                 389
#define IDB_Road_CUp                    390
#define IDB_Road_LDownCorner            391
#define IDB_Road_LUpCorner              392
#define IDB_Road_RDownCorner            393
#define IDB_Road_RUpCorner              394
#define IDB_Road_CLeft                  395
#define IDB_Road_Right                  396
#define IDB_Road_CRight                 396
#define IDB_Tool_axe                    397
#define IDB_Tool_bell                   398
#define IDB_Tool_hammer                 399
#define IDB_Tool_hoe                    400
#define IDB_Tool_milkMachine            401
#define IDB_Tool_rod                    402
#define IDB_Tool_scissor                403
#define IDB_Tool_sickle                 404
#define IDB_Tool_WtrCan                 405
#define IDB_BITMAP40                    406
#define IDB_Tool_box                    406
#define IDB_STOREHouse                  407
#define IDB_BITMAP41                    408
#define IDB_HmHouse                     408
#define IDB_BITMAP42                    409
#define IDB_B_About                     409
#define IDB_BITMAP43                    410
#define IDB_MAIN_POINT                  410
#define IDB_B_Des_P1                    411
#define IDB_B_Des_P2                    412
#define IDB_B_Des_P3                    413
#define IDB_B_Des_P4                    414
#define IDB_BITMAP49                    416
#define IDB_Ach_Chicken                 417
#define IDB_Ach_Cow                     418
#define IDB_Ach_Crop                    419
#define IDB_Ach_Money                   420
#define IDB_BITMAP48                    421
#define IDB_Ach_Sheep                   421
#define IDB_BITMAP50                    426
#define IDB_Ach_Win_1                   429
#define IDB_Ach_Win_2                   430
#define IDB_Ach_Win_3                   431
#define IDB_Ach_Win_4                   432
#define IDB_Ach_Win_5                   433
#define IDB_BITMAP44                    434
#define IDB_Ach_Win_0                   434
#define IDB_Ach_Des_Chicken             435
#define IDB_Ach_Des_Cow                 436
#define IDB_Ach_Des_Crop                437
#define IDB_Ach_Des_Money               438
#define IDB_BITMAP52                    439
#define IDB_Ach_Des_Sheep               439
#define IDB_Over_Win_YorN               440
#define IDB_Over_Win_YorN_NClick        441
#define IDB_Over_Win_YorN_YClick        443
#define IDB_BITMAP53                    444
#define IDB_BITMAP45                    445
#define IDB_Over_Win_Cul                445
#define IDB_B_Des_P5                    450
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        451
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
